### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by JXFOnestep** [jan9419/ORB_SLAM3_Monodepth#3]
Thanks for your great work first.
I met some problem in DepthEstimator::EstimateDepth()

terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA error: no kernel image is available for execution on the device

My libtorch version is 1.8.0 with cuda11.1, and my pytorch version is all 1.8.0.
I have no idea to fix it, can you help me?

**Comment by JXFOnestep** [comment]
I fix it by using libtorch1.8.1 with cuda11.1.
Btw, what's your GPU?

**Comment by jan9419** [comment]
Sorry for the late reply, I was busy at work. I am glad to hear that the problem has been solved. I have an NVIDIA GeForce GTX 1650.
